apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops
  name: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gitops
  template:
    metadata:
      labels:
        app: hello-gitops
      annotations:
        seccomp.security.kubernetes.io/pod: "docker/default"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - image: hello-gitops
        name: hello-gitops
        ports:
          - name: http
            containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
+           memory: 256Mi
          limits:
            cpu: 0.5
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: my-registry-creds
